"""empty message

Revision ID: 866f063ff004
Revises: 556c61c845eb
Create Date: 2019-03-14 15:22:50.840257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '866f063ff004'
down_revision = '556c61c845eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delivery_ibfk_2', 'delivery', type_='foreignkey')
    op.drop_constraint('delivery_ibfk_1', 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'job_id')
    op.drop_column('delivery', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('delivery', sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('delivery_ibfk_1', 'delivery', 'job', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('delivery_ibfk_2', 'delivery', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
