"""empty message

Revision ID: 8fadcae83523
Revises: 866f063ff004
Create Date: 2019-03-14 15:31:30.520508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fadcae83523'
down_revision = '866f063ff004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('delivery', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('delivery', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery', 'job', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'delivery', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'user_id')
    op.drop_column('delivery', 'job_id')
    op.drop_column('delivery', 'company_id')
    # ### end Alembic commands ###
